### PR TITLE
chore: refactor ordering/naming of markdown files

### PR DESCRIPTION
**Pull request by danisharora099**
This PR addresses moving away from the `1.md` etc filenames used for ordering.

Previously, it made reviewing quite hard as the whole content of each file is changed, and it's hard to be sure if it's on purpose or if just some sections were re-ordered/shifted.

This PR depends on https://github.com/waku-org/waku.guide/pull/24 to be merged first for a merge to master.

### CODE REVIEW

**Comment by fryorcraken** [comment]
@danisharora099 I would suggest to keep PRs that are not against master or pending on another PR to be merged to be marked as "draft" as the PR is not ready to be reviewed for a merge against current master.

**Comment by danisharora099** [comment]
> @danisharora099 I would suggest to keep PRs that are not against master or pending on another PR to be merged to be marked as "draft" as the PR is not ready to be reviewed for a merge against current master.

Sure.
This is a PR to `feat/improvements` which means there are two ways to go about it:
1. Merge `feat/improvements` to`master`, pull latest `master` in current branch and review diff
2. Merge the current branch with `feat/improvements`, and then merge that to master

I am indifferent to the approaches. 
Assuming it's the former, I shall keep followups as draft! :D

**Comment by fryorcraken** [comment]
Yes, I think the former is more straightforward because then you end up with a huge PR against master.

**Comment by danisharora099** [comment]
superseded by https://github.com/waku-org/waku.guide/pull/29

**Pull request closed without merging**
