### PR TITLE
Use Logos v1 theme

### PR DESCRIPTION
**Pull request by jeangovil**

### CODE REVIEW

**Comment by fryorcraken** [comment]
@LordGhostX once you have done #63 could you check this and provide feedback?

**Comment by fryorcraken** [comment]
- Black theme does not work great on the "Powered by Waku" page with the logos
- dead link afaik.institute. What is that?
- what is this "log in to comment" pop up? I would prefer to direct discussions to GitHub or Discord (or is that a Vercel thing?)
- In light mode, the underlying is too light so it's hard to see that something is a hyperlink

**Comment by amirhouieh** [comment]
You can merge already and meantime we taking care of the design issues, should be ready in 1 or 2 days. 
https://github.com/acid-info/logos-docusaurus-plugins/issues/24
https://github.com/acid-info/logos-docusaurus-plugins/issues/25

- as for "log in to comment" is actually not part of design, its from Vercel! please ignore it! once we move out of Vercel it will be gone.

**Comment by LordGhostX** [comment]
Comments on the recent commits: 

1. There's a `yt-video` class on the videos on the `/presentations` page. Let's add the effect back.

```css
.yt-video {
    max-width: 100%;
    width: 640px;
    height: 360px;
}
```

2. There's a GitHub icon in the navbar with the `header-github-link` class. Let's bring it back.

Before:
Screenshot 2023-06-09 at 03 20 44

Now:
Screenshot 2023-06-09 at 03 21 05

Here's the CSS:

```css
.header-github-link:before {
	content: '';
	width: 24px;
	height: 24px;
	display: flex;
	background: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E")
    no-repeat;
}

html[data-theme='dark'] .header-github-link:before {
	background: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='white' d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E")
    no-repeat;
}
```

**Comment by fryorcraken** [comment]
@LordGhostX we've been asked to provide feedback as issues in https://github.com/acid-info/logos-docusaurus-plugins/issues

Can you please create new issues for the 2 points you have raised?

**Comment by amirhouieh** [comment]
@fryorcraken could you please merge this pr to develop branch? Infra team needs this in order to finish the deployment pipeline.

**Comment by LordGhostX** [comment]
@amirhouieh what's the difference between the `acid-info:docu-2023` branch and the [waku-org:docu-2023](https://github.com/acid-info/waku.guide/tree/docu-2023) branch? Is it possible to merge the latter instead?

**Comment by amirhouieh** [comment]
> @amirhouieh what's the difference between the `acid-info:docu-2023` branch and the [waku-org:docu-2023](https://github.com/acid-info/waku.guide/tree/docu-2023) branch? Is it possible to merge the latter instead?

@LordGhostX previously, our dev team member did not have access to repo on Waku space and hence cerated a fork on our own Space. But thats is not an issue and we keep pushing to both repos. You can consider `waku-org:docu-2023` as the working one.

**Comment by fryorcraken** [comment]
Superseded by #68

**Pull request closed without merging**
