### PR TITLE
Move `About` folder to home

### PR DESCRIPTION
**Pull request by fryorcraken**

### CODE REVIEW

**Comment by fryorcraken** [comment]
@amirhouieh how do I check why Vercel fails? Docusaurus is fine locally.

**Comment by danisharora099** [comment]
> @amirhouieh how do I check why Vercel fails? Docusaurus is fine locally.

one of the links on the markdown was broken -- pushed a commit to address that.
running `yarn build` locally helps check what caused a fail.

but it would definitely be nice to have access to vercel to check things on the fly.

**Review by danisharora099 — APPROVED** [review]
Looks good!

**Comment by fryorcraken** [comment]
> but it would definitely be nice to have access to vercel to check things on the fly.

@amirhouieh is that an option?

**Pull request merged**
