### PR TITLE
add network diagram

### PR DESCRIPTION
**Pull request by fryorcraken**
Ref  #7 tackling:

> (1) Message flow architecture diagram:
	- Shows Waku Relay and pubsub topic message routing
	- Shows Filter/Light Push/Store usage with content topic usage/filtering.
	- could include information about transports used (tcp, websocket) if does not make it too busy
	- Include adaptive node information: cloud vs laptop (native) vs mobile vs browser
>  (2) architecture diagram of Discovery: DNS Discovery + Discv5 + peer exchange + peer persistence

Review tip: click "view file" to have GitHub render the mermaid code.

### CODE REVIEW

**Comment by fryorcraken** [comment]
@jm-clius, can you please check accuracy?

@LordGhostX , What do you think re readability?

**Comment by jm-clius** [comment]
Accuracy LGTM!

Minor things that could be ambiguous:
- in adaptive nodes there could in theory be redundant connections from resource-restricted clients to relay nodes
- in adaptive nodes there could be diagonal connectivity between the mesh nodes as well
- in discv5 each response could contain the address of more than just one discovered peer

I imagine though that adding the above would make diagrams less readable, so feel free to ignore.

**Comment by LordGhostX** [comment]
LGTM too. A couple of comments:

1. David was mentioned in Peer Exchange (response from Bob) but not in the diagram. Can we let Alice dial David instead of Bob again?
2. Is replacing complex entries like `prod.waku.nodes.status.im` in DNS Discovery with a simpler one possible? Can we simplify the response represented by `enrtree-root:v1 e=U3...3Y ...`? I need help understanding these entries.

**Comment by fryorcraken** [comment]
> LGTM too. A couple of comments:
> 
>     1. David was mentioned in Peer Exchange (response from Bob) but not in the diagram. Can we let Alice dial David instead of Bob again?

Well spotted, corrected.

>     2. Is replacing complex entries like `prod.waku.nodes.status.im` in DNS Discovery with a simpler one possible? Can we simplify the response represented by `enrtree-root:v1 e=U3...3Y ...`? I need help understanding these entries.

At this point in time we want to give a general idea to the user that several DNS queries are needed to retrieve ENR info form a domain name.
Hence I think we should keep the steps. However, I am happy to make the content simpler.

Spec: https://eips.ethereum.org/EIPS/eip-1459#dns-record-structure

First query gets the `enrtree-root`. this contains value `e` for the `enr-root`

Second query use the value in `e`: `U3...3Y` to retrieve the information, etc

I will add a step by step explanation of the diagram to the file

**Comment by fryorcraken** [comment]
> Accuracy LGTM!
> 
> Minor things that could be ambiguous:
> 
>     * in adaptive nodes there could in theory be redundant connections from resource-restricted clients to relay nodes
>     * in adaptive nodes there could be diagonal connectivity between the mesh nodes as well

I am considering dropping this graph in favour of https://miro.com/app/board/uXjVMOLf330=/?share_link_id=79505572021

>     * in discv5 each response could contain the address of more than just one discovered peer
> 
> 
> I imagine though that adding the above would make diagrams less readable, so feel free to ignore.

Yes I was thinking the same. accuracy vs readability

**Comment by fryorcraken** [comment]
Feedback integrated.

@LordGhostX wdyt? 

As per https://github.com/waku-org/waku.guide/issues/62 I suggest to use Miro board diagrams to provide architecture overview of Waku. Meaning we drop `adaptive_nodes.mmd` diagram.

Regarding discovery, I would suggest to include the 3 diagrams I have done in a _discovery_ section of the docs. I think it's an important concept to cover few points:
- how we are decentralizing Waku
- how restricted environment reduce decentralization property
- Latency expectations when bootstrapping a node (and maybe we can add more info there)

**Comment by LordGhostX** [comment]
I'm happy to take over once it's merged :muscle:

**Pull request merged**
